# Generated by Django 4.2.2 on 2023-08-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='Reference',
        ),
    ]
