# Generated by Django 4.2.2 on 2023-08-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_enrollment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='img',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
    ]
